-- Runs identically against local Postgres 16 (docker-compose.yml) and Aurora
-- Serverless v2 PostgreSQL.
--
-- Every row in every table is synthetic, generated by scripts/seed.py. There is no
-- real client, person or engagement in this repo because there never was one.
--
-- Primary keys are plain integers assigned by the generator rather than identity
-- columns. A sequence assigned id is a sequence dependent checksum, and the seed has
-- to be reproducible down to the byte.

drop table if exists invoices cascade;
drop table if exists time_entries cascade;
drop table if exists sow_line_items cascade;
drop table if exists engagements cascade;
drop table if exists people cascade;
drop table if exists clients cascade;

create table clients (
    id       integer primary key,
    name     text    not null,
    segment  text    not null
        check (segment in ('enterprise', 'mid_market', 'public_sector', 'non_profit'))
);

create table people (
    id         integer       not null primary key,
    name       text          not null,
    role       text          not null
        check (role in ('partner', 'principal', 'senior_consultant', 'consultant', 'analyst')),
    cost_rate  numeric(10,2) not null check (cost_rate > 0),
    bill_rate  numeric(10,2) not null check (bill_rate > 0)
);

create table engagements (
    id              integer       not null primary key,
    client_id       integer       not null references clients (id),
    name            text          not null,
    sow_ref         text          not null unique,
    fee_type        text          not null check (fee_type in ('fixed', 'time_and_materials')),
    ceiling_hours   numeric(10,2) not null check (ceiling_hours > 0),
    ceiling_amount  numeric(12,2) not null check (ceiling_amount > 0),
    start_date      date          not null,
    end_date        date          not null,
    status          text          not null check (status in ('active', 'completed', 'on_hold')),
    check (end_date >= start_date)
);

-- No constraint ties status to end_date. An engagement whose end_date has passed while
-- status is still 'active' is a real state in every time system there is.

create table sow_line_items (
    id              integer       not null primary key,
    engagement_id   integer       not null references engagements (id),
    deliverable     text          not null,
    hours_budgeted  numeric(10,2) not null check (hours_budgeted > 0),
    amount          numeric(12,2) not null check (amount >= 0),
    due_date        date          not null
);

create table time_entries (
    id             integer      not null primary key,
    person_id      integer      not null references people (id),
    engagement_id  integer      not null references engagements (id),
    entry_date     date         not null,
    hours          numeric(5,2) not null check (hours > 0),

    -- Nullable on purpose. Mess case 5 seeds entries where nobody set the flag, and a
    -- NOT NULL here would make that state unrepresentable and the data_quality block
    -- pointless.
    billable       boolean,

    note           text,

    -- Load-bearing, and the reason it is a separate column rather than a derived one:
    -- when the work happened and when it was filed are different facts. Late-arriving
    -- data is only representable because these can disagree, and half the seeded mess
    -- depends on that.
    submitted_at   timestamptz  not null
);

create table invoices (
    id             integer       not null primary key,
    engagement_id  integer       not null references engagements (id),
    period         date          not null,  -- first day of the month invoiced
    amount         numeric(12,2) not null check (amount >= 0),
    status         text          not null check (status in ('issued', 'paid', 'void')),
    issued_at      date          not null,
    paid_at        date,
    check (paid_at is null or paid_at >= issued_at),
    check ((status = 'paid') = (paid_at is not null))
);

-- Indexes sized for the queries the four tools actually run: aggregation over a period
-- for a set of engagements, per-person concentration within an engagement, and the
-- late-arrival scan that compares submitted_at against the period boundary.
create index time_entries_engagement_date_idx on time_entries (engagement_id, entry_date);
create index time_entries_person_date_idx     on time_entries (person_id, entry_date);
create index time_entries_submitted_at_idx    on time_entries (submitted_at);
create index invoices_engagement_period_idx   on invoices (engagement_id, period);
create index engagements_client_status_idx    on engagements (client_id, status);
